export const environment = {
  production: true,
  SERVER_ADDRESS: "https://api.signdesk.in",
  ENVIRONMENT: "production",
  CLIENT_URL: "https://signdesk.in/workflow",
  MONOLITHIC_CLIENT_URL: "https://signdesk.in/app/#/",
  CLM_CLIENT_URL: "https://signdesk.in/clm/#/",
  ICICI_CLIENT_URL: "https://signdesk.in/icici/#/",
  KYC_APPLICATION_URL: "https://signdesk.in/kyc/#/",
  EMANDATE_APPLICATION_URL: "https://signdesk.in/emandate/#/",
  STAMP_DUTY_CAL_SERVER_ADDRESS: "https://in-accounts.signdesk.com",
  STAMP_DUTY_CAL_CLIENT_URL: "https://in.signdesk.com",
  FLE_CLIENT_URL: "https://signdesk.in/app-v2/#",
  UAT_CONSENT_ID: "62662d1ebf79abb61aad04a2",
  REQUEST_UID: "4eXgShgL7506Qcz/Ye031lj0c7KBnbzyYfCNqSKMIMk=",
  CIPHER_KEY: "Q5mo=2WMXKAwmTkbwBlftGd6LVZjVKXh",
  RAND_1: "Q5mo=2WMX",
  RAND_2: "KAwmTkbwBlftG",
  RAND_3: "d6LVZjVKXh",
};